"use client";

import { useEffect, useState } from "react";
import { RegisteredModel } from "@/lib/providers/types";
import { getProvider } from "@/lib/providers";
import { useAppStore } from "@/lib/store";
import {
  Database,
  MessageSquare,
  BarChart3,
  Download,
  Loader2,
  PlusCircle,
} from "lucide-react";
import Link from "next/link";
import { toast } from "sonner";

export default function ModelsPage() {
  const { useLocalProvider } = useAppStore();
  const [models, setModels] = useState<RegisteredModel[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadModels() {
      try {
        const provider = getProvider(useLocalProvider);
        const data = await provider.getModels();
        setModels(data);
      } catch (err: any) {
        console.error("Failed to load models:", err);
      } finally {
        setLoading(false);
      }
    }
    loadModels();
  }, [useLocalProvider]);

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200/80 pb-5">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            <Database className="h-6 w-6 text-blue-600" />
            Model Registry
          </h1>
          <p className="text-xs text-slate-500 mt-1">
            Registered and active AI systems generated by EasyLLM.
          </p>
        </div>
        <Link
          href="/"
          className="inline-flex items-center gap-2 rounded-full bg-blue-600 px-5 py-2.5 text-xs font-semibold text-white shadow-md shadow-blue-500/20 hover:bg-blue-700 transition"
        >
          <PlusCircle className="h-4 w-4" />
          Create New AI
        </Link>
      </div>

      {loading ? (
        <div className="flex h-64 items-center justify-center gap-3">
          <Loader2 className="h-6 w-6 animate-spin text-blue-600" />
          <p className="text-sm font-medium text-slate-500">Loading registered models...</p>
        </div>
      ) : models.length === 0 ? (
        <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center shadow-sm">
          <Database className="mx-auto h-12 w-12 text-slate-400" />
          <h3 className="mt-4 text-base font-bold text-slate-800">No Models Registered Yet</h3>
          <p className="mt-1 text-xs text-slate-500 max-w-md mx-auto">
            Use the Architect workflow to build your first RAG knowledge assistant or fine-tuned QLoRA model.
          </p>
          <Link
            href="/"
            className="mt-5 inline-flex items-center gap-2 rounded-full bg-blue-600 px-5 py-2 text-xs font-semibold text-white hover:bg-blue-700 transition shadow-sm"
          >
            Build First Model
          </Link>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {models.map((model) => (
            <div
              key={model.id}
              className="flex flex-col justify-between rounded-2xl border border-slate-200 bg-white p-5 hover:border-slate-300 transition shadow-sm"
            >
              <div>
                <div className="flex items-center justify-between">
                  <span
                    className={`rounded-full px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-wider ${
                      model.architecture === "rag"
                        ? "bg-blue-50 text-blue-700 border border-blue-200"
                        : model.architecture === "qlora"
                        ? "bg-purple-50 text-purple-700 border border-purple-200"
                        : "bg-amber-50 text-amber-700 border border-amber-200"
                    }`}
                  >
                    {model.architecture}
                  </span>
                  <span className="text-[10px] font-mono text-slate-400">{model.id}</span>
                </div>

                <h3 className="mt-3 text-base font-bold text-slate-900 leading-snug">{model.name}</h3>
                
                <div className="mt-3 space-y-1.5 text-xs text-slate-600 border-t border-slate-100 pt-3">
                  <div className="flex justify-between">
                    <span className="text-slate-400">Base Model:</span>
                    <span className="font-mono font-semibold text-slate-800">{model.base_model.split("/").pop()}</span>
                  </div>
                  {model.dataset_name && (
                    <div className="flex justify-between">
                      <span className="text-slate-400">Dataset:</span>
                      <span className="text-slate-800 font-medium truncate max-w-[150px]">{model.dataset_name}</span>
                    </div>
                  )}
                  {model.training_time_seconds && (
                    <div className="flex justify-between">
                      <span className="text-slate-400">Training Time:</span>
                      <span className="font-mono text-slate-800 font-semibold">{model.training_time_seconds}s</span>
                    </div>
                  )}
                  {model.evaluation && (
                    <div className="flex justify-between items-center">
                      <span className="text-slate-400">Eval Score:</span>
                      <span className="font-mono text-emerald-700 font-bold">
                        {model.evaluation.overall_custom_score}%
                      </span>
                    </div>
                  )}
                </div>
              </div>

              <div className="mt-5 pt-3 border-t border-slate-100 flex items-center gap-2">
                <Link
                  href={`/playground/${model.id}`}
                  className="flex-1 flex items-center justify-center gap-1.5 rounded-full bg-blue-600 px-4 py-2 text-xs font-semibold text-white hover:bg-blue-700 transition shadow-2xs"
                >
                  <MessageSquare className="h-3.5 w-3.5" />
                  Chat
                </Link>
                {model.evaluation && (
                  <Link
                    href={`/evaluation/${model.id}`}
                    className="flex items-center justify-center rounded-full border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-100 transition"
                  >
                    <BarChart3 className="h-3.5 w-3.5 text-emerald-600" />
                  </Link>
                )}
                {model.adapter_path && (
                  <button
                    onClick={() => toast.success(`Adapter located at: ${model.adapter_path}`)}
                    title="Model Adapter Artifact"
                    className="flex items-center justify-center rounded-full border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-100 transition"
                  >
                    <Download className="h-3.5 w-3.5" />
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
